# Liquent Cluster Configuration - Rolling Upgrade Suite
# Generated by render_config.py — do not edit directly

[cluster]
name = "liquent-devnet-rolling-upgrade"
base_dir = "/tmp/liquent-cluster-rolling-upgrade"

[genesis_source]
genesis_path = "./artifacts/genesis.json"
waypoint_path = "./artifacts/waypoint.txt"

# ============ Genesis Nodes (node1-node4) ============

[[nodes]]
id = "node1"
host = "127.0.0.1"
role = "genesis"
source = {{SOURCE}}
validator_port = 6180
vfn_port = 6190
rpc_port = 8545
metrics_port = 9001
inspection_port = 10000
https_port = 1024
authrpc_port = 8561
reth_p2p_port = 12024

[[nodes]]
id = "node2"
host = "127.0.0.1"
role = "genesis"
source = {{SOURCE}}
validator_port = 6181
vfn_port = 6191
rpc_port = 8546
metrics_port = 9002
inspection_port = 10001
https_port = 1025
authrpc_port = 8562
reth_p2p_port = 12025

[[nodes]]
id = "node3"
host = "127.0.0.1"
role = "genesis"
source = {{SOURCE}}
validator_port = 6182
vfn_port = 6192
rpc_port = 8547
metrics_port = 9003
inspection_port = 10002
https_port = 1026
authrpc_port = 8563
reth_p2p_port = 12026

[[nodes]]
id = "node4"
host = "127.0.0.1"
role = "genesis"
source = {{SOURCE}}
validator_port = 6183
vfn_port = 6193
rpc_port = 8548
metrics_port = 9004
inspection_port = 10003
https_port = 1027
authrpc_port = 8564
reth_p2p_port = 12027

# ============ Validator Node (node5) ============

[[nodes]]
id = "node5"
host = "127.0.0.1"
role = "validator"
source = {{SOURCE}}
validator_port = 6184
vfn_port = 6194
rpc_port = 8549
metrics_port = 9005
inspection_port = 10004
https_port = 1028
authrpc_port = 8565
reth_p2p_port = 12028

# ============ Full Node (vfn1) ============

[[nodes]]
id = "vfn1"
host = "127.0.0.1"
role = "vfn"
source = {{SOURCE}}
vfn_port = 6195
rpc_port = 8550
metrics_port = 9006
inspection_port = 10005
https_port = 1029
authrpc_port = 8566
reth_p2p_port = 12029

[faucet_init]
num_accounts = 1
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
eth_balance = "10000000000000000000000"
